# Generated by Django 5.1.6 on 2025-02-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên Phòng Khám')),
                ('address', models.CharField(max_length=255, verbose_name='Địa Chỉ Phòng Khám')),
                ('phone', models.CharField(max_length=15, verbose_name='Số Điện Thoại Phòng Khám')),
                ('license_number', models.CharField(max_length=50, verbose_name='Giấy Phép Phòng Khám')),
            ],
            options={
                'verbose_name': 'Phòng Khám',
                'verbose_name_plural': 'Danh Sách Phòng Khám',
            },
        ),
    ]
