# Generated by Django 5.1.6 on 2025-02-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinic',
            options={},
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='license_number',
        ),
        migrations.AddField(
            model_name='clinic',
            name='license',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
