# Generated by Django 5.1.6 on 2025-02-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_clinic_options_remove_clinic_license_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinic',
            options={},
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='clinic',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
