# Generated by Django 5.1.4 on 2025-02-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_clinic_email_alter_clinic_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('customer', 'Khách hàng'), ('dentist', 'Nha sĩ'), ('admin', 'Quản lý')], default='customer', max_length=10),
        ),
    ]
